#pragma config(Sensor, in1,    l1,             sensorLineFollower)
#pragma config(Sensor, in2,    l2,             sensorLineFollower)
#pragma config(Sensor, dgtl2,  in,             sensorSONAR_inch)
#pragma config(Sensor, dgtl9,  button,         sensorDigitalIn)
#pragma config(Motor,  port1,           lm,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rm,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
int time = 0;
int speed = 59;
while(1)
{
	if(SensorValue(l1) > 2200 || SensorValue(l2) > 2200)
	{
		speed = -speed;
		motor[lm] = speed;
		motor[rm] = speed;
		sleep(500);
	}
	motor[lm] = speed;
	motor[rm] = speed;

	sleep(time);
	//if the button is pressed make the robot stop by making the speed 0
	if(SensorValue(button) == 0)
	{
		speed = 0;
}
}
}
